object Versions {
    const val kotlin = "1.5.20"
    const val jetpackCore = "1.7.0"
    const val appcompat = "1.4.0"
    const val material = "1.4.0"
    const val activity = "1.4.0"
    const val constraintLayout = "2.1.2"
    const val lifecycle = "2.4.0"

    const val kotlinSerialization = "1.3.1"
    const val gradle = "7.0.3"
    const val jetpackCompose = "1.1.0-beta01"
    const val accompanist = "0.21.3-beta"

    const val retrofit = "2.9.0"
    const val rxJava = "2.2.21"
    const val rxJavaAndroid = "2.1.1"
    const val okHttp = "5.0.0-alpha.3"
    const val hilt = "2.40.3"
    const val koin = "3.1.4"
    const val exoPlayer = "2.16.1"
    const val room = "2.3.0"
    const val glide = "4.12.0"
    const val glideJC = "1.4.4"
}
